version: '3.8'

services:
  api:
    build: .
    container_name: keyword-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "[dbname]://[userid]:[password]@[serverIP]:3306/[Database]"
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      ENABLE_SCHEDULER: "true"
      BATCH_SIZE: "10"
      SYNC_INTERVAL: "3600"
      PYTHONPATH: /app:/app/src
    restart: unless-stopped
